<?php

namespace Container65xXH2b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UxSqzVtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uxSqzVt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uxSqzVt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordEncoder' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'resetPasswordRepo' => ['privates', 'App\\Repository\\ResetPasswordRepository', 'getResetPasswordRepositoryService', true],
        ], [
            'passwordEncoder' => '?',
            'resetPasswordRepo' => 'App\\Repository\\ResetPasswordRepository',
        ]);
    }
}
