<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container65xXH2b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container65xXH2b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container65xXH2b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container65xXH2b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container65xXH2b\App_KernelDevDebugContainer([
    'container.build_hash' => '65xXH2b',
    'container.build_id' => 'f0e8e695',
    'container.build_time' => 1631524343,
], __DIR__.\DIRECTORY_SEPARATOR.'Container65xXH2b');
